mysite/forum/urls.py
from django.urls import path

from . import views

# Below are different url paths.
app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:thread_id>/', views.detail, name='detail'),
    path('<int:thread_id>/charts', views.pie_chart, name='pie_chart'),
    path('users', views.users, name='users'),
    path('<int:thread_id>/watch_update/', views.watch_update, name='watch_update'),
    path('watch', views.watch, name='watch')
]

mysite/mysite/urls.py
# The include() function allows referencing other URLconfs. Whenever Django encounters
# include(), it chops off whatever part of the URL matched up to that point and sends
# the remaining string to the included URLconf for further processing.

# The idea behind include() is to make it easy to plug-and-play URLs. Since forum are in
# their own URLconf (forum/urls.py), they can be placed under “/forum/”, or under “/fun_polls/”,
# or under “/content/forum/”, or any other path root, and the app will still work.


from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('forum/', include('forum.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

# Below are different url paths.
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:thread_id>/', views.detail, name='detail'),
    path('<int:thread_id>/charts', views.pie_chart, name='pie_chart'),
    path('users', views.users, name='users')
]

mysite/polls/views.py
import pandas as pd
from django.shortcuts import get_object_or_404, render
import nltk
from nltk.corpus import stopwords
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Posts
from .models import Threads


def index(request):
    # order threads by date_time. notice the '-' im front of 'last_date_scraped. The '-' orders it by DESC.
    threads_list = Threads.objects.order_by('-last_date_scraped')
    # get the page number from the URL
    page_number = request.GET.get('page', 1)
    # https://www.geeksforgeeks.org/how-to-add-pagination-in-django-project/
    # paginator takes list of objects as first argument and number per page as second
    paginator = Paginator(threads_list, 50)
    # will use this to prevent every page number from showing in pagination. Will only get numbers on either side of
    # current page
    # https://docs.djangoproject.com/en/3.2/ref/paginator/#django.core.paginator.Paginator.get_elided_page_range
    # https://nemecek.be/blog/105/how-to-use-elided-pagination-in-django-and-solve-too-many-pages-problem
    pagination_page_range = paginator.get_elided_page_range(number=page_number)

    try:
        thread_info = paginator.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        thread_info = paginator.page(1)
    except EmptyPage:
        # if page is empty then return last page
        thread_info = page_number.page(paginator.num_pages)
    context = {'pagination_page_range': pagination_page_range, 'threads': thread_info}

    # The render() function takes the request object as its first argument, a template name
    # as its second argument and a dictionary as its optional third argument. It returns an
    # HttpResponse object of the given template rendered with the given context.
    return render(request, 'polls/index.html', context)


def detail(request, thread_id):
    # if will run when filtering by username
    if request.method == 'POST':
        username_filter = request.POST['fname']

        # posts should be changed to post_list. This section is interim until i figure out pagination
        posts = Posts.objects.filter(thread_id=thread_id).filter(username=username_filter).order_by('date_time')
        thread_info = Threads.objects.get(thread_id=thread_id)
        context = {'posts': posts, 'thread_info': thread_info}
        return render(request, 'polls/detail.html', context)
    else:  # get the replies from the thread
        post_list = Posts.objects.filter(thread_id=thread_id).order_by('date_time')

    # get data for the thread so that you can display information for it in charts.html
    thread_info = Threads.objects.get(thread_id=thread_id)

    # get the page number from the URL
    page_number = request.GET.get('page', 1)

    # https://www.geeksforgeeks.org/how-to-add-pagination-in-django-project/
    # paginator takes list of objects as first argument, and number of pages for second
    paginator = Paginator(post_list, 49)
    # will use this to prevent every page number from showing in pagination. Will only get numbers on either side of
    # current page
    # https: // docs.djangoproject.com / en / 3.2 / ref / paginator /  # django.core.paginator.Paginator.get_elided_page_range
    # https://nemecek.be/blog/105/how-to-use-elided-pagination-in-django-and-solve-too-many-pages-problem
    pagination_page_range = paginator.get_elided_page_range(number=page_number)

    try:
        posts = paginator.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is empty then return the last page
        posts = page_number.page(paginator.num_pages)
    context = {'pagination_page_range': pagination_page_range, 'posts': posts, 'thread_info': thread_info}
    return render(request, 'polls/detail.html', context)


# Tutorial for visualizing using charts.js
# https://simpleisbetterthancomplex.com/tutorial/2020/01/19/how-to-use-chart-js-with-django.html
def pie_chart(request, thread_id):
    # if statement will run when a date range is submitted on the charts page. This will filter out any posts not
    # within the date range. For date_picker_end_date I hardcode seconds i.e. ':59'. This is because a user can only
    # enter hours and minutes in the range field, the seconds will default to ':00', but I want all the posts for
    # that minute so I add :59 seconds. e.g. it will search 1:15:00, but I want all replies that occurred during the
    # 15 minute mark e.g. a post at 1:15:30 will not get included.
    if request.method == 'POST' and 'start_date' in request.POST:
        date_picker_start_date = request.POST['start_date']
        date_picker_end_date = request.POST['end_date'] + ':59'
        replies_from_thread_df = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).filter(
            date_time__gte=date_picker_start_date, date_time__lte=date_picker_end_date).values())

    # statement will run if username is submitted in the form. Will only show charts for this username
    elif request.method == 'POST' and 'fname' in request.POST:
        username_filter = request.POST['fname']
        replies_from_thread_df = pd.DataFrame.from_records(
            Posts.objects.filter(thread_id=thread_id).filter(username=username_filter).values())
    # will filter out quoted replies if Include Quoted Replies box is Yes or No
    elif request.method == 'POST' and 'quote_filter' in request.POST:
        quote_filter = request.POST['quote_filter']
        print(quote_filter)
        if quote_filter == 'no':
            replies_from_thread_df = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).values())
            replies_from_thread_df = replies_from_thread_df[replies_from_thread_df["quoted"] == "No quote"]
            print('no')
        else:
            replies_from_thread_df = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).values())
            print("yes")

    # will run when page first loads, and no form submissions have been made on the page.
    else:
        # after thread link is clicked, use thread_id to filter replies for only that thread.
        # Convert this returned sql to a dataframe
        # https://stackoverflow.com/questions/11697887/converting-django-queryset-to-pandas-dataframe
        replies_from_thread_df = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).values())

    # dates for the date range picker forms
    date_of_first_reply_in_date_range = replies_from_thread_df.date_time.min()
    date_of_last_reply_in_date_range = replies_from_thread_df.date_time.max()

    # get the dates of the first and last replies posted
    df_for_getting_dates = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).values())
    date_of_first_reply = df_for_getting_dates.date_time.min()
    date_of_last_reply = df_for_getting_dates.date_time.max()

    # get data for the thread so that you can display information for it in charts.html
    thread_info = Threads.objects.get(thread_id=thread_id)

    # labels to pass to charts.html for the sentiment pie chart
    sentiment_pie_chart_labels = ["Positive", "Negative", "Neutral"]

    # pie chart sentiment with quotes and with out quotes i.e. all replies
    # find the number of occurrences of Pos, Neg, Neut in sentiment column.
    quotes_sentiment_count_list = []
    quotes_df = replies_from_thread_df
    for sentiment in sentiment_pie_chart_labels:
        if sentiment in quotes_df['sentiment'].values:
            quotes_sentiment_count_list.append(quotes_df['sentiment'].value_counts()[sentiment])
        else:
            quotes_sentiment_count_list.append(0)

    # pie chart sentiment without quoted replies
    # find the number of occurrences of Pos, Neg, Neut in sentiment column.
    no_quotes_sentiment_count_list = []
    no_quotes_df = replies_from_thread_df[replies_from_thread_df["quoted"] == "No quote"]
    for sentiment in sentiment_pie_chart_labels:
        if sentiment in no_quotes_df['sentiment'].values:
            no_quotes_sentiment_count_list.append(no_quotes_df['sentiment'].value_counts()[sentiment])
        else:
            no_quotes_sentiment_count_list.append(0)

    # Total Replies on a day in Chron order bar chart
    # Groupby Day using freq='D' and then find the size() and add it to the column Total Replies which will tally
    # the total replies for each day. Convert the .size() series that it returns to a dataframe using .reset_index.
    # Convert DateTime object to just date using strftime. groupby day and show daily Total Replies. if there is only
    # one date worth of replies, use the if statement to group by hours instead to display hourly data for the single
    # day.
    total_replies_datetime_df = replies_from_thread_df.set_index("date_time").groupby(pd.Grouper(freq='D')).size(). \
        reset_index(name='total replies')
    total_replies_datetime_df["date_time"] = (total_replies_datetime_df["date_time"].dt.strftime('%Y-%m-%d'))

    # This date will be the x-axis title if there is only one day of Replies
    if len(total_replies_datetime_df["date_time"]) == 1:
        total_replies_datetime_df = replies_from_thread_df.set_index("date_time").groupby(
            pd.Grouper(freq='H')).size().reset_index(name='total replies')

        total_replies_datetime_df["date_time"] = (total_replies_datetime_df["date_time"].dt.strftime('%H:%M:%S'))

    total_replies_datetime_bar_chart_labels = total_replies_datetime_df["date_time"].tolist()
    total_replies_datetime_bar_chart_data = total_replies_datetime_df["total replies"].tolist()

    # find the average sentiment score for each day

mysite/polls/templates/polls/charts.html
<!--charts.js tutorial https://simpleisbetterthancomplex.com/tutorial/2020/01/19/how-to-use-chart-js-with-django.html-->
<!--https://stackoverflow.com/questions/24555823/multiple-chartjs-in-the-same-page/40401048-->
<!--format datetime for html form https://stackoverflow.com/questions/63099974/django-template-convert-datetime-local-format-->
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <style>
  #margins {
  margin: 10px;
  }
</style>
</head>

<body>
<!--nav bar -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'polls:index'%}">Threads</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'polls:users'%}">Users</a>
    </li>
  </ul>
</nav>

<div id="margins">
<h2> {{ thread_info.title }} </h2>
<a href="{% url 'polls:detail' thread_info.thread_id %}">Replies for Thread</a>
<br>
<br>
{% block content %}
<!--form that will filter date range of posts -->
<form method="POST">{% csrf_token %}
  <p><input type = 'datetime-local'  name='start_date'
                      value="{{date_of_first_reply_in_date_range|date:'Y-m-d'}}T{{date_of_first_reply_in_date_range|time:'H:i'}}"
                      min="{{date_of_first_reply|date:'Y-m-d'}}T{{date_of_first_reply|time:'H:i'}}"
                      max="{{date_of_last_reply|date:'Y-m-d'}}T{{date_of_last_reply|time:'H:i'}}">
  </p>
  <p><input type = 'datetime-local'  name='end_date'
                    value="{{date_of_last_reply_in_date_range|date:'Y-m-d'}}T{{date_of_last_reply_in_date_range|time:'H:i'}}"
                    min="{{date_of_first_reply|date:'Y-m-d'}}T{{date_of_first_reply|time:'H:i'}}"
                    max="{{date_of_last_reply|date:'Y-m-d'}}T{{date_of_last_reply|time:'H:i'}}">

  <button type="submit" class="btn btn-primary"> Submit</button>
    <a href="{% url 'polls:pie_chart' thread_info.thread_id %}">Max Range</a>
  </p>
</form>


<!--filter by username form-->
<div class=form-group">
<form method="POST">{% csrf_token %}
  <input type="text" id="fname" name="fname" class="form-control-md" placeholder="Username">
  <button type="submit" class="btn btn-primary"> Submit</button>
  <a href="{% url 'polls:pie_chart' thread_info.thread_id %}">Show All</a>
</form>
</div>

<!--Include/Exclude quoted replies dropdown -->
<div class="form-group form-inline">
<form method="POST">{% csrf_token %}
  <label for="quote_filter">Include Quoted Replies: </label>
  <select id="quote_filter" name="quote_filter" class="form-control" style="width:auto;">
      <option disabled selected value>-</option>
      <option value="yes">Yes</option>
      <option value="no">No</option>
  </select>
  <button type="submit" class="btn btn-primary"> Submit</button>
</form>
</div>

<!--closing tag for <div style='margins'>-->
</div>

<!-- add the charts.js library to page -->
<!-- create two variables (sentiment_for_quotes, sentiment_for_no_quotes) that will use the data passed from views.py
pie_chart method to create pie charts using the charts.js lib -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

<br>
<div id="container_1" style="width: 60%; margin: 0 auto;">
<canvas id="total-replies-datetime-bar-canvas"></canvas>
</div>
  <script>
  var total_replies_datetime_bar = {
      type: 'line',
      data: {
        datasets: [{
          data: {{ total_replies_datetime_bar_chart_data|safe }},
          pointRadius: 2,
          pointHoverRadius: 5,
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1,
          label: 'Total Replies',
          fill: 'false'
        }],
        labels: {{ total_replies_datetime_bar_chart_labels|safe }}
      },
      options: {
        title: {
            display: true,
            text: 'Replies'
         },
        scales: {
          responsive: true,
          yAxes: [{
            ticks: {
                //will start the bar chart at zero
                beginAtZero: true,
                //precision 0 will for only integers i.e. will not use 1.5
                precision: 0,
            }
          }]
        }
      }
    };
    </script>
<!--
<br>
<div id="container_6" style="width: 60%; margin: 0 auto;">
<canvas id="daily-average-sentiment-line-canvas"></canvas>
</div>
  <script>
  var daily_average_sentiment_line = {
      type: 'line',
      data: {
        datasets: [{
          data: {{ daily_sentiment_average_df_line_chart_data|safe }},
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1,
          label: 'Average Score',
          fill: 'false'
        }],
        labels: {{ daily_sentiment_average_df_line_chart_labels|safe }}
      },
      options: {
        title: {
            display: true,
            text: 'Sentiment'
         },
        scales: {
          responsive: true,
          yAxes: [{
            ticks: {
                //will start the bar chart at zero
                beginAtZero: true,
                suggestedMax: 1,
                suggestedMin: -1

            }
          }]
        }
      }
    };
    </script>
-->
<br>
<div id="container_7" style="width: 60%; margin: 0 auto;">
<canvas id="daily-total-sentiment-stacked-bar-canvas"></canvas>
</div>
  <script>
  var daily_total_sentiment_stacked_bar = {
      type: 'bar',
      data: {
      labels: {{ total_daily_sentiment_stacked_bar_chart_labels|safe }},
        datasets: [{
         label: 'Negative',
         backgroundColor: "#FF7F7F",
          data: {{ total_daily_sentiment_stacked_bar_chart_negative_data|safe }},
          },
          {
          label: 'Neutral',
          backgroundColor: "#FFF9A6",
          data: {{ total_daily_sentiment_stacked_bar_chart_neutral_data|safe }},
          },
          {
          label: 'Positive',
          backgroundColor: "#56d798",
          data: {{ total_daily_sentiment_stacked_bar_chart_positive_data|safe }},
        }],
      },
options: {
title: {
    display: true,
    text: 'Sentiment'
    },
    scales: {
      xAxes: [{
        stacked: true,
        gridLines: {
          display: false,
        }
      }],
      yAxes: [{
        stacked: true,
        ticks: {
          beginAtZero: true,
        },
        type: 'linear',
      }]
    },
    responsive: true,
  }
};
</script>
<br>

<div id="container_3" style="width: 60%; margin: 0 auto;">
<canvas id="total-replies-username-bar-canvas"></canvas>
</div>
  <script>
  var total_replies_username_bar = {
      type: 'bar',
      data: {
        datasets: [{
          data: {{ total_replies_by_username_data|safe }},
          //using a single color without an array[] will cause all bars to be the same color
          backgroundColor:
            '#fdd835',
          label: 'Total Replies'
        }],
        labels: {{ total_replies_by_username_labels|safe }}
      },
      options: {
        title: {
            display: true,
            text: 'User Total Replies'
         },
        responsive: true,
        scales: {
          yAxes: [{
            ticks: {
                //will start the bar chart at zero
                beginAtZero: true,
                //precision 0 will for only integers i.e. will not use 1.5
                precision: 0,
            }
          }]
        }
      }
    };
    </script>
<br>
<div id="container_4" style="width: 60%; margin: 0 auto;">
<canvas id="most-frequent-words-bar-canvas"></canvas>
</div>
  <script>
  var most_frequent_words_bar = {
      type: 'horizontalBar',
      data: {
        datasets: [{
          data: {{ most_frequent_words_sorted_df_data|safe }},
          //using a single color without an array[] will cause all bars to be the same color
          backgroundColor:
            '#90EE90',
          label: 'Word Total'
        }],
        labels: {{ most_frequent_words_sorted_df_labels|safe }}
      },
      options: {
        title: {
            display: true,
            text: 'Most Frequent Words'
         },
        responsive: true,
        scales: {
          xAxes: [{
            ticks: {
                //will start the bar chart at zero
                beginAtZero: true,
                //precision 0 will for only integers i.e. will not use 1.5
                precision: 0,
            }
          }]
        }
      }
    };
</script>
<br>
<div id="container_5" style="width: 60%; margin: 0 auto;">
<canvas id="sentiment-for-quotes-pie-canvas"></canvas>
</div>
  <script>
    var sentiment_for_quotes_pie = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ quotes_sentiment_count_list|safe }},
          backgroundColor: [
          "#56d798",
          "#FF7F7F",
          "#FFF9A6"
          ],
          label: 'Sentiment'
        }],
        labels: {{ sentiment_pie_chart_labels|safe }}
      },
      options: {
        responsive: true,
        title: {
            display: true,
            text: 'Total Sentiment'
        }
      }
    };

      window.onload = function() {

      var ctx = document.getElementById('sentiment-for-quotes-pie-canvas').getContext('2d');
      window.myPie = new Chart(ctx, sentiment_for_quotes_pie);

      var ctx_3 = document.getElementById('total-replies-datetime-bar-canvas').getContext('2d');
      window.myBar = new Chart(ctx_3, total_replies_datetime_bar);

      var ctx_4 = document.getElementById('total-replies-username-bar-canvas').getContext('2d');
      window.myBar_2 = new Chart(ctx_4, total_replies_username_bar);

      var ctx_5 = document.getElementById('most-frequent-words-bar-canvas').getContext('2d');
      window.myBar_3 = new Chart(ctx_5, most_frequent_words_bar);

      /*
      var ctx_6 = document.getElementById('daily-average-sentiment-line-canvas').getContext('2d');
      window.myLine = new Chart(ctx_6, daily_average_sentiment_line);
      */

      var ctx_7 = document.getElementById('daily-total-sentiment-stacked-bar-canvas').getContext('2d');
      window.myStacked = new Chart(ctx_7, daily_total_sentiment_stacked_bar);
    };

  </script>

{% endblock %}
</body>

mysite/polls/templates/polls/detail.html
<!-- this is bootstrap4. may not work with other versions
https://simpleisbetterthancomplex.com/tutorial/2016/08/03/how-to-paginate-with-django.html-->
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        #margins {
        margin: 10px;
       }
    </style>
</head>

<!--nav bar -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'polls:index'%}">Threads</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'polls:users'%}">Users</a>
    </li>
  </ul>
</nav>

<div id="margins">
<!--the table class below uses bootstrap to format the table. The first set of <th> tags are columns names. The following
<td> tags use django variables that display the data in the specified column names. The first set of <td> tags
 add the thread creators post to the table, all of the other replies are looped through and added to the table.-->
<br>
<h3>{{ thread_info.title }}</h3>
<a href="{% url 'polls:pie_chart' thread_info.thread_id %}">Charts for Thread</a>
<br>
<br>

<!--filter by username form-->
<div class=form-group">
<form method="POST">{% csrf_token %}
  <input type="text" id="fname" name="fname" class="form-control-md" placeholder="Username">
  <button type="submit" class="btn btn-primary"> Submit</button>
    <a href="{% url 'polls:detail' thread_info.thread_id %}">Show All</a>
</form>
</div>

<br>
<div>
<table class="table table-bordered">
  <thead>
    <tr>
        <th>Username</th>
        <th>Quoted</th>
        <th>Reply</th>
        <th>Sentiment</th>
        <th>Score</th>
        <th>Date</th>
        <th>Page</th>
    </tr>
  </thead>
  <tbody>
  <!--Use this if statement to only show the thread creators reply in the table on the first page -->
    {% if posts.number == 1 %}
       <tr>
          <td>{{ thread_info.username }} (OP)</td>
          <td></td>
          <td>{{ thread_info.replies }}</td>
          <td></td>
          <td></td>
          <td>{{ thread_info.date_time|date:'Y-m-d H:i' }}</td>
          <td></td>
      </tr>
    {% endif %}
    {% for post in posts %}
      <tr>
          <td>{{ post.username }}</td>
          <td>{{ post.quoted }}</td>
          <td>{{ post.replies }}</td>
          <td>{{ post.sentiment }}</td>
          <td>{{ post.score }}</td>
          <td>{{ post.date_time|date:'Y-m-d H:i' }}</td>
          <td>{{ post.thread_page }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<!-- below is pagination code. I use the Paginator class and get_elided_page_range in views.py to format the pagination
This code uses bootstrap and prevents all pages from showing if there are several pages.-->
<div>
  <ul class="pagination justify-content-center flex-wrap mt-2 mb-4">
    {% if posts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for post in pagination_page_range %}
      {% if posts.number == post %}
        <li class="active page-item"><span class="page-link">{{ post }}<span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ post }}">{{ post }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
</div>

<!-- closing tag for div id="margins> -->
</div>

mysite/polls/templates/polls/users.html
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <style>
      #margins {
      margin: 10px;
      }
    </style>
</head>

<!--nav bar -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'polls:index'%}">Threads</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'polls:users'%}">Users</a>
    </li>
  </ul>
</nav>

<div id="margins">
<br>
<div class=form-group">
<form method="POST">{% csrf_token %}
  <input type="text" id="fname" name="fname" class="form-control-md" placeholder="Username">
  <button type="submit" class="btn btn-primary"> Submit</button>
</form>
</div>
<br>




<!--the table class below uses bootstrap to format the table. The first set of <th> tags are columns names. The following
<td> tags use django variables that display the data in the specified column names-->
<div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Thread Title</th>
      <th>Replies</th>
    </tr>
  </thead>
  <tbody>
    {% for thread_title, total_replies, thread_id in zipped_replies_title_list %}
      <tr>
        <td><a href="{% url 'polls:detail' thread_id %}"> {{ thread_title }} </a></td>
        <td>{{ total_replies }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>

<!--closing tag for div id="margins" -->
</div>