mysite/forum/urls.py
from django.urls import path

from . import views

# Below are different url paths.
app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:thread_id>/', views.detail, name='detail'),
    path('<int:thread_id>/charts', views.pie_chart, name='pie_chart'),
    path('users', views.users, name='users'),
    path('<int:thread_id>/watch_update/', views.watch_update, name='watch_update'),
    path('watch', views.watch, name='watch')
]

mysite/mysite/urls.py
# The include() function allows referencing other URLconfs. Whenever Django encounters
# include(), it chops off whatever part of the URL matched up to that point and sends
# the remaining string to the included URLconf for further processing.

# The idea behind include() is to make it easy to plug-and-play URLs. Since forum are in
# their own URLconf (forum/urls.py), they can be placed under “/forum/”, or under “/fun_polls/”,
# or under “/content/forum/”, or any other path root, and the app will still work.


from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('forum/', include('forum.urls')),
    path('admin/', admin.site.urls),
]

mysite/forum/models.py
# python manage.py dbshell

import datetime
from django.db import models
from django.utils import timezone


# This table has an 'id' column
# This model is for the thread title and post by thread creator
class Threads(models.Model):
    thread_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50)
    date_time = models.DateTimeField()
    replies = models.CharField(max_length=5000)
    url = models.CharField(max_length=200, unique=True)
    title = models.CharField(max_length=1000)
    last_page_scraped = models.CharField(max_length=5000)
    last_date_scraped = models.DateTimeField()  # most recent date that the thread was scraped
    total_views = models.CharField(max_length=500000000)
    reply_rate_percentage = models.CharField(max_length=100000, null=True, blank=True) # this will need to allow null values
    total_replies = models.CharField(max_length=5000000, null=True, blank=True) # this will need to allow null values
    total_distinct_usernames = models.CharField(max_length=100000, null=True, blank=True) # this will need to allow null values
    percent_distinct_replies = models.CharField(max_length=1000, null=True, blank=True) # this will need to allow null values
    watch_list = models.CharField(max_length=3)

    # This method is for a test
    def was_created_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_time <= now

    def __str__(self):
        return self.username


# This table has a 'id' column foreign keys to 'id' in threads table
# This models if for all the replies to a thread
class Posts(models.Model):
    username = models.CharField(max_length=50)
    date_time = models.DateTimeField()
    # Django automatically appends '_id' to the end of foreign key column names. So to access this
    # you will need to use thread_id
    # https://docs.djangoproject.com/en/dev/ref/models/fields/#database-representation
    thread = models.ForeignKey(Threads, on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=6, decimal_places=4)
    quoted = models.CharField(max_length=8)
    sentiment = models.CharField(max_length=10)
    thread_page = models.CharField(max_length=10000)  # page number that the reply appears on
    replies = models.CharField(max_length=10000)

    # you can only select one primary key in a Django model. UniqueConstraint allows you to set two unique values (
    # works like a composite key). It is not possible for a user to  post at the same date_time, so this will serve as
    # a unique key so a users posts are not saved twice to the DB
    class Meta:
        constraints = [models.UniqueConstraint(fields=['username', 'date_time'], name='composite_key')]

    def __str__(self):
        return self.username

mysite/forum/views.py
import pandas as pd
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
import nltk
from django.urls import reverse
from nltk.corpus import stopwords
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect

from .models import Posts
from .models import Threads


def index(request):
    # order threads by date_time. notice the '-' im front of 'last_date_scraped. The '-' orders it by DESC.
    threads_list = Threads.objects.order_by('-last_date_scraped')
    # get the page number from the URL
    page_number = request.GET.get('page', 1)
    # https://www.geeksforgeeks.org/how-to-add-pagination-in-django-project/
    # paginator takes list of objects as first argument and number per page as second
    paginator = Paginator(threads_list, 50)
    # will use this to prevent every page number from showing in pagination. Will only get numbers on either side of
    # current page
    # https://docs.djangoproject.com/en/3.2/ref/paginator/#django.core.paginator.Paginator.get_elided_page_range
    # https://nemecek.be/blog/105/how-to-use-elided-pagination-in-django-and-solve-too-many-pages-problem
    pagination_page_range = paginator.get_elided_page_range(number=page_number)
    try:
        thread_info = paginator.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        thread_info = paginator.page(1)
    except EmptyPage:
        # if page is empty then return last page
        thread_info = page_number.page(paginator.num_pages)
    context = {'pagination_page_range': pagination_page_range, 'threads': thread_info}
    # The render() function takes the request object as its first argument, a template name
    # as its second argument and a dictionary as its optional third argument. It returns an
    # HttpResponse object of the given template rendered with the given context.
    return render(request, 'forum/index.html', context)


def detail(request, thread_id):
    # if will run when username is submitted in form
    if request.method == 'GET' and 'fname' in request.GET:
        username_filter = request.GET.get('fname')
        replies = Posts.objects.filter(thread_id=thread_id).filter(username=username_filter).order_by('date_time')
        thread_info = Threads.objects.get(thread_id=thread_id)
        context = {'replies': replies, 'thread_info': thread_info}
        return render(request, 'forum/detail.html', context)
    else:  # get the replies from the thread
        replies_list = Posts.objects.filter(thread_id=thread_id).order_by('date_time')
    # get data for the thread so that you can display information for it in charts.html
    thread_info = Threads.objects.get(thread_id=thread_id)
    # get the page number from the URL
    page_number = request.GET.get('page', 1)
    # https://www.geeksforgeeks.org/how-to-add-pagination-in-django-project/
    # paginator takes list of objects as first argument, and number of pages for second
    paginator = Paginator(replies_list, 49)
    # will use this to prevent every page number from showing in pagination. Will only get numbers on either side of
    # current page
    # https: // docs.djangoproject.com / en / 3.2 / ref / paginator /  # django.core.paginator.Paginator.get_elided_page_range
    # https://nemecek.be/blog/105/how-to-use-elided-pagination-in-django-and-solve-too-many-pages-problem
    pagination_page_range = paginator.get_elided_page_range(number=page_number)
    try:
        replies = paginator.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        replies = paginator.page(1)
    except EmptyPage:
        # if page is empty then return the last page
        replies = page_number.page(paginator.num_pages)
    context = {'pagination_page_range': pagination_page_range, 'replies': replies, 'thread_info': thread_info}
    return render(request, 'forum/detail.html', context)


# Tutorial for visualizing using charts.js
# https://simpleisbetterthancomplex.com/tutorial/2020/01/19/how-to-use-chart-js-with-django.html
def pie_chart(request, thread_id):
    # if statement will run when a date range is submitted on the charts page. This will filter out any posts not
    # within the date range. For date_picker_end_date I hardcode seconds i.e. ':59'. This is because a user can only
    # enter hours and minutes in the range field, the seconds will default to ':00', but I want all the posts for
    # that minute so I add :59 seconds. e.g. it will search 1:15:00, but I want all replies that occurred during the
    # 15 minute mark e.g. a post at 1:15:30 will not get included.
    if request.method == 'GET' and 'start_date' in request.GET:
        date_picker_start_date = request.GET.get('start_date')
        date_picker_end_date = request.GET.get('end_date') + ':59'
        replies_from_thread_df = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).filter(
            date_time__gte=date_picker_start_date, date_time__lte=date_picker_end_date).values())

    # statement will run if username is submitted in the form. Will only show charts for this username
    elif request.method == 'GET' and 'fname' in request.GET:
        username_filter = request.GET.get('fname')
        replies_from_thread_df = pd.DataFrame.from_records(
            Posts.objects.filter(thread_id=thread_id).filter(username=username_filter).values())
        # data dictionary len will be 0 if username does not exist. reload page in this case.
        if len(replies_from_thread_df) == 0:
            # raise Http404("Username Not Found")
            return redirect(request.path_info)

    # will filter out quoted replies if Include Quoted Replies box is Yes or No
    elif request.method == 'GET' and 'quote_filter' in request.GET:
        quote_filter = request.GET.get('quote_filter')
        if quote_filter == 'no':
            replies_from_thread_df = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).values())
            replies_from_thread_df = replies_from_thread_df[replies_from_thread_df["quoted"] == "No quote"]
        else:
            replies_from_thread_df = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).values())

    # will run when page first loads, and no form submissions have been made on the page.
    else:
        # after thread link is clicked, use thread_id to filter replies for only that thread.
        # Convert this returned sql to a dataframe
        # https://stackoverflow.com/questions/11697887/converting-django-queryset-to-pandas-dataframe
        replies_from_thread_df = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).values())

    # dates for the date range picker forms
    date_of_first_reply_in_date_range = replies_from_thread_df.date_time.min()
    date_of_last_reply_in_date_range = replies_from_thread_df.date_time.max()

    # get the dates of the first and last replies posted
    df_for_getting_dates = pd.DataFrame.from_records(Posts.objects.filter(thread_id=thread_id).values())
    date_of_first_reply = df_for_getting_dates.date_time.min()
    date_of_last_reply = df_for_getting_dates.date_time.max()

    # get data for the thread so that you can display information for it in charts.html
    thread_info = Threads.objects.get(thread_id=thread_id)

    # labels to pass to charts.html for the sentiment pie chart
    sentiment_pie_chart_labels = ["Positive", "Negative", "Neutral"]

    # pie chart sentiment with quotes and with out quotes i.e. all replies
    # find the number of occurrences of Pos, Neg, Neut in sentiment column.
    quotes_sentiment_count_list = []
    quotes_df = replies_from_thread_df
    for sentiment in sentiment_pie_chart_labels:
        if sentiment in quotes_df['sentiment'].values:
            quotes_sentiment_count_list.append(quotes_df['sentiment'].value_counts()[sentiment])
        else:
            quotes_sentiment_count_list.append(0)

    # pie chart sentiment without quoted replies
    # find the number of occurrences of Pos, Neg, Neut in sentiment column.
    no_quotes_sentiment_count_list = []
    no_quotes_df = replies_from_thread_df[replies_from_thread_df["quoted"] == "No quote"]
    for sentiment in sentiment_pie_chart_labels:
        if sentiment in no_quotes_df['sentiment'].values:
            no_quotes_sentiment_count_list.append(no_quotes_df['sentiment'].value_counts()[sentiment])
        else:
            no_quotes_sentiment_count_list.append(0)

    # Total Replies on a day in Chron order bar chart
    # Groupby Day using freq='D' and then find the size() and add it to the column Total Replies which will tally
    # the total replies for each day. Convert the .size() series that it returns to a dataframe using .reset_index.
    # Convert DateTime object to just date using strftime. groupby day and show daily Total Replies. if there is only
    # one date worth of replies, use the if statement to group by hours instead to display hourly data for the single
    # day.
    total_replies_datetime_df = replies_from_thread_df.set_index("date_time").groupby(pd.Grouper(freq='D')).size(). \
        reset_index(name='total replies')
    total_replies_datetime_df["date_time"] = (total_replies_datetime_df["date_time"].dt.strftime('%Y-%m-%d'))

    # This date will be the x-axis title if there is only one day of Replies
    if len(total_replies_datetime_df["date_time"]) == 1:
        total_replies_datetime_df = replies_from_thread_df.set_index("date_time").groupby(
            pd.Grouper(freq='H')).size().reset_index(name='total replies')

        total_replies_datetime_df["date_time"] = (total_replies_datetime_df["date_time"].dt.strftime('%H:%M:%S'))

    total_replies_datetime_bar_chart_labels = total_replies_datetime_df["date_time"].tolist()

mysite/forum/templates/forum/charts.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}">
<!--charts.js tutorial https://simpleisbetterthancomplex.com/tutorial/2020/01/19/how-to-use-chart-js-with-django.html-->
<!--https://stackoverflow.com/questions/24555823/multiple-chartjs-in-the-same-page/40401048-->
<!--format datetime for html form https://stackoverflow.com/questions/63099974/django-template-convert-datetime-local-format-->
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
<!--nav bar -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'forum:index'%}">Threads</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'forum:users'%}">Users</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'forum:watch'%}">Watching</a>
    </li>
  </ul>
</nav>

<div id="margins">
<h2> {{ thread_info.title }} </h2>
<a href="{% url 'forum:detail' thread_info.thread_id %}">Replies for this thread</a>
<br>
<br>
{% block content %}
<!--form that will filter date range of posts -->
<form method="GET">
  <p><input type = 'datetime-local'  name='start_date'
                      value="{{date_of_first_reply_in_date_range|date:'Y-m-d'}}T{{date_of_first_reply_in_date_range|time:'H:i'}}"
                      min="{{date_of_first_reply|date:'Y-m-d'}}T{{date_of_first_reply|time:'H:i'}}"
                      max="{{date_of_last_reply|date:'Y-m-d'}}T{{date_of_last_reply|time:'H:i'}}">
  </p>
  <p><input type = 'datetime-local'  name='end_date'
                    value="{{date_of_last_reply_in_date_range|date:'Y-m-d'}}T{{date_of_last_reply_in_date_range|time:'H:i'}}"
                    min="{{date_of_first_reply|date:'Y-m-d'}}T{{date_of_first_reply|time:'H:i'}}"
                    max="{{date_of_last_reply|date:'Y-m-d'}}T{{date_of_last_reply|time:'H:i'}}">

  <button type="submit" class="btn btn-primary"> Submit</button>
    <a href="{% url 'forum:pie_chart' thread_info.thread_id %}">Max Range</a>
  </p>
</form>


<!--filter by username form-->
<div class=form-group">
<form method="GET">
  <input type="text" id="fname" name="fname" class="form-control-md" placeholder="Username">
  <button type="submit" class="btn btn-primary"> Submit</button>
  <a href="{% url 'forum:pie_chart' thread_info.thread_id %}">Show All</a>
</form>
</div>

<!--Include/Exclude quoted replies dropdown -->
<div class="form-group form-inline">
<form method="GET">
  <label for="quote_filter">Include Quoted Replies: </label>
  <select id="quote_filter" name="quote_filter" class="form-control" style="width:auto;">
      <option disabled selected value>-</option>
      <option value="yes">Yes</option>
      <option value="no">No</option>
  </select>
  <button type="submit" class="btn btn-primary"> Submit</button>
</form>
</div>

<!--closing tag for <div style='margins'>-->
</div>

<!-- add the charts.js library to page -->
<!-- create two variables (sentiment_for_quotes, sentiment_for_no_quotes) that will use the data passed from views.py
pie_chart method to create pie charts using the charts.js lib -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

<br>
<div id="container_1" style="width: 60%; margin: 0 auto;">
<canvas id="total-replies-datetime-bar-canvas"></canvas>
</div>
  <script>
  var total_replies_datetime_bar = {
      type: 'line',
      data: {
        datasets: [{
          data: {{ total_replies_datetime_bar_chart_data|safe }},
          pointRadius: 2,
          pointHoverRadius: 5,
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1,
          label: 'Total Replies',
          fill: 'false'
        }],
        labels: {{ total_replies_datetime_bar_chart_labels|safe }}
      },
      options: {
        title: {
            display: true,
            text: 'Replies'
         },
        scales: {
          responsive: true,
          yAxes: [{
            ticks: {
                //will start the bar chart at zero
                beginAtZero: true,
                //precision 0 will for only integers i.e. will not use 1.5
                precision: 0,
            }
          }]
        }
      }
    };
    </script>
<!--
<br>
<div id="container_6" style="width: 60%; margin: 0 auto;">
<canvas id="daily-average-sentiment-line-canvas"></canvas>
</div>
  <script>
  var daily_average_sentiment_line = {
      type: 'line',
      data: {
        datasets: [{
          data: {{ daily_sentiment_average_df_line_chart_data|safe }},
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1,
          label: 'Average Score',
          fill: 'false'
        }],
        labels: {{ daily_sentiment_average_df_line_chart_labels|safe }}
      },
      options: {
        title: {
            display: true,
            text: 'Sentiment'
         },
        scales: {
          responsive: true,
          yAxes: [{
            ticks: {
                //will start the bar chart at zero
                beginAtZero: true,
                suggestedMax: 1,
                suggestedMin: -1

            }
          }]
        }
      }
    };
    </script>
-->
<br>
<div id="container_7" style="width: 60%; margin: 0 auto;">
<canvas id="daily-total-sentiment-stacked-bar-canvas"></canvas>
</div>
  <script>
  var daily_total_sentiment_stacked_bar = {
      type: 'bar',
      data: {
      labels: {{ total_daily_sentiment_stacked_bar_chart_labels|safe }},
        datasets: [{
         label: 'Negative',
         backgroundColor: "#FF7F7F",
          data: {{ total_daily_sentiment_stacked_bar_chart_negative_data|safe }},
          },
          {
          label: 'Neutral',
          backgroundColor: "#FFF9A6",
          data: {{ total_daily_sentiment_stacked_bar_chart_neutral_data|safe }},
          },
          {
          label: 'Positive',
          backgroundColor: "#56d798",
          data: {{ total_daily_sentiment_stacked_bar_chart_positive_data|safe }},
        }],
      },
options: {
title: {
    display: true,
    text: 'Sentiment'
    },
    scales: {
      xAxes: [{
        stacked: true,
        gridLines: {
          display: false,
        }
      }],
      yAxes: [{
        stacked: true,
        ticks: {
          beginAtZero: true,
        },
        type: 'linear',
      }]
    },
    responsive: true,
  }
};
</script>
<br>

<div id="container_3" style="width: 60%; margin: 0 auto;">
<canvas id="total-replies-username-bar-canvas"></canvas>
</div>
  <script>
  var total_replies_username_bar = {
      type: 'bar',
      data: {
        datasets: [{
          data: {{ total_replies_by_username_data|safe }},
          //using a single color without an array[] will cause all bars to be the same color
          backgroundColor:
            '#fdd835',
          label: 'Total Replies'
        }],
        labels: {{ total_replies_by_username_labels|safe }}
      },
      options: {
        title: {
            display: true,
            text: 'User Total Replies'
         },
        responsive: true,
        scales: {
          yAxes: [{
            ticks: {
                //will start the bar chart at zero
                beginAtZero: true,
                //precision 0 will for only integers i.e. will not use 1.5
                precision: 0,
            }
          }]
        }
      }
    };
    </script>
<br>
<div id="container_4" style="width: 60%; margin: 0 auto;">
<canvas id="most-frequent-words-bar-canvas"></canvas>
</div>
  <script>
  var most_frequent_words_bar = {
      type: 'horizontalBar',
      data: {
        datasets: [{
          data: {{ most_frequent_words_sorted_df_data|safe }},
          //using a single color without an array[] will cause all bars to be the same color
          backgroundColor:
            '#90EE90',
          label: 'Word Total'
        }],
        labels: {{ most_frequent_words_sorted_df_labels|safe }}
      },
      options: {
        title: {
            display: true,
            text: 'Most Frequent Words'
         },
        responsive: true,
        scales: {
          xAxes: [{
            ticks: {
                //will start the bar chart at zero
                beginAtZero: true,
                //precision 0 will for only integers i.e. will not use 1.5
                precision: 0,
            }
          }]
        }
      }
    };
</script>
<br>
<div id="container_5" style="width: 60%; margin: 0 auto;">
<canvas id="sentiment-for-quotes-pie-canvas"></canvas>
</div>
  <script>
    var sentiment_for_quotes_pie = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ quotes_sentiment_count_list|safe }},
          backgroundColor: [
          "#56d798",
          "#FF7F7F",
          "#FFF9A6"
          ],
          label: 'Sentiment'
        }],
        labels: {{ sentiment_pie_chart_labels|safe }}
      },
      options: {
        responsive: true,
        title: {
            display: true,
            text: 'Total Sentiment'
        }
      }
    };

      window.onload = function() {

      var ctx = document.getElementById('sentiment-for-quotes-pie-canvas').getContext('2d');
      window.myPie = new Chart(ctx, sentiment_for_quotes_pie);

      var ctx_3 = document.getElementById('total-replies-datetime-bar-canvas').getContext('2d');
      window.myBar = new Chart(ctx_3, total_replies_datetime_bar);

      var ctx_4 = document.getElementById('total-replies-username-bar-canvas').getContext('2d');
      window.myBar_2 = new Chart(ctx_4, total_replies_username_bar);

      var ctx_5 = document.getElementById('most-frequent-words-bar-canvas').getContext('2d');
      window.myBar_3 = new Chart(ctx_5, most_frequent_words_bar);

      /*
      var ctx_6 = document.getElementById('daily-average-sentiment-line-canvas').getContext('2d');
      window.myLine = new Chart(ctx_6, daily_average_sentiment_line);
      */

      var ctx_7 = document.getElementById('daily-total-sentiment-stacked-bar-canvas').getContext('2d');
      window.myStacked = new Chart(ctx_7, daily_total_sentiment_stacked_bar);
    };

  </script>

{% endblock %}
</body>

mysite/forum/templates/forum/watch.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}">

<!-- this is bootstrap4. may not work with other versions
https://simpleisbetterthancomplex.com/tutorial/2016/08/03/how-to-paginate-with-django.html-->
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<!--nav bar -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'forum:index'%}">Threads</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'forum:users'%}">Users</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'forum:watch'%}">Watching</a>
    </li>
  </ul>
</nav>

<div id="margins">
<!--the table class below uses bootstrap to format the table. The first set of <th> tags are columns names. The following
<td> tags use django variables that display the data in the specified column names-->
<div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Thread Title</th>
      <th>Pages</th>
      <th>Creator</th>
      <th>Created</th>
      <th>Views</th>
      <th>Replies</th>
      <th>View/Reply Rate (est.)</th>
      <th>Distinct Usernames</th>
      <th>Distinct Replies</th>
      <th>Charts</th>
    </tr>
  </thead>
  <tbody>
    {% for thread in threads %}
      <tr>
        <td><a href="{% url 'forum:detail' thread.thread_id %}">{{ thread.title }}</a>
          {% if thread.watch_list == 'no' %}
          <form action="{% url 'forum:watch_update' thread.thread_id %}" method="POST">{% csrf_token %}
            <button class="btn btn-link" type="submit" value="yes" name="watch-2"><i class="far fa-eye"></i></button>
          </form></td>
          {% else %}
          <form action="{% url 'forum:watch_update' thread.thread_id %}" method="POST">{% csrf_token %}
            <button class="btn btn-link" type="submit" value="no" name="watch-2"><i class="fas fa-eye"></i></button>
          </form></td>
          {% endif %}
        <td>{{ thread.last_page_scraped }}</td>
        <td>{{ thread.username }}</td>
        <td>{{ thread.date_time|date:'Y-m-d' }}</td>
        <td>{{ thread.total_views }}</td>
        <td>{{ thread.total_replies }}</td>
        <td>{{ thread.reply_rate_percentage }}%</td>
        <td>{{ thread.total_distinct_usernames }}</td>
        <td>{{ thread.percent_distinct_replies }}%</td>
        <td><a href="{% url 'forum:pie_chart' thread.thread_id %}">Charts</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<!-- below is pagination code. I use the Paginator class and get_elided_page_range in views.py to format the pagination
This code uses bootstrap and prevents all pages from showing if there are several pages.-->
<div>
  <ul class="pagination justify-content-center flex-wrap mt-2 mb-4">
    {% if threads.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ threads.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for thread in pagination_page_range|default_if_none:threads.paginator.get_elided_page_range %}
      {% if threads.number == thread %}
         <li class="active page-item"><span class="page-link">{{ thread }}<span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ thread }}">{{ thread }}</a></li>
      {% endif %}
    {% endfor %}
    {% if threads.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ threads.next_page_number }}">&raquo;</a></li>
    {% else %}
     <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
</div>

<!--closing tag for div id="margins"> -->
</div>